<a href="https://colab.research.google.com/github/tomasbsm/Modelo-Recomendacao/blob/main/Day_07_Din%C3%A2mica_Tom%C3%A1s5140.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1. Blibiotecas e Importando as bases de dados

In [1]:
from google.colab import drive
drive.mount('/content/drive')
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
# Add some convenience functions to Pandas DataFrame.
pd.options.display.max_rows = 10
pd.options.display.float_format = '{:.3f}'.format

sns.set(rc={'figure.figsize':(11.7,8.27)}) # isso é pras figuras ficarem maiores

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
df_itens = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/DNC_order_items_dataset.csv')
df_reviews = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/DNC_order_reviews_dataset.csv')
df_orders = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/DNC_orders_dataset.csv')
df_products = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/DNC_products_dataset.csv')

In [3]:
df_itens.head()

# order_id - Id do pedido de compra;
# order_item_id - Número de produtos em uma mesma compra;
# product_id - Id do produto;
# price - preço;

Unnamed: 0  ...   price
0           0  ...  58.900
1           1  ... 239.900
2           2  ... 199.000
3           3  ...  12.990
4           4  ... 199.900

[5 rows x 5 columns]

In [4]:
df_reviews.head()

#review_id - Id do review
#order_id - Id do pedido de compra
#review_score - Resulado do review

Unnamed: 0  ... review_score
0           0  ...            4
1           1  ...            5
2           2  ...            5
3           3  ...            5
4           4  ...            5

[5 rows x 4 columns]

In [5]:
df_orders.head()

# order_id - Id do pedido de compra
# customer_id - Id do consumidor que realizou a compra
# order_status - Status de Compra

Unnamed: 0  ... order_status
0           0  ...    delivered
1           1  ...    delivered
2           2  ...    delivered
3           3  ...    delivered
4           4  ...    delivered

[5 rows x 4 columns]

In [6]:
df_products.head()

#product_id - Id do produto
#product_category_name - Categoria do produto
#product_name_length - Tamanho do nome do produto
#product_description_length - Tamanho do nome do produto
#product_weigth_g - Peso do produto (em gramas)
#product_lenght_cm - Comprimento do produto (em cm)
#product_width_cm - Largura do produto (em cm)

Unnamed: 0  ... product_width_cm
0           0  ...           14.000
1           1  ...           20.000
2           2  ...           15.000
3           3  ...           26.000
4           4  ...           13.000

[5 rows x 9 columns]

#2. Definição do modelo
Com a base de dados disponibilizada, quais modeos de recomendação podem ser feitos?

**OFERECER O PRODUTO CERTO PARA A PESSOA CERTA**

**Qual é o melhor momento para rodar o modelo de recomendação?**

Em propagandas?

Quando o cliente estiver fazendo a pesquisa? 

Quando o cliente estiver vendo um produto?


## 2.1. Insights

1- Para oferecer o produto certo, precisa-se saber quais são os produtos que se parecem um com o outro (matriz de simaliridade). Para recomendar o produto para a pessoa certa, precisa-se saber qual o tipo de cliente com que ele se parece (matriz de simalaridade).

2- Além disso, esse modelo deve rodar enquanto o cliente estiver vendo um produto, pois nosso modelo de recomendação irá se basear em produtos similares!

#3. Exploração dos Dados
O que os dados nos dizem? Quais são as hipóteses que podem ser levantadas disso? Será que os dados são suficientes para o modelo que se propôs a fazer?

In [7]:
df_itens_original = df_itens.copy()
df_reviews_original = df_reviews.copy()
df_products_original = df_products.copy()
df_orders_original = df_orders.copy()

In [8]:
df_itens.shape

(112650, 5)

In [9]:
df_reviews.shape

(99224, 4)

In [10]:
df_products.shape

(32951, 9)

In [11]:
df_orders.shape

(99441, 4)

##3.1. Dataset de Reviews

In [12]:
df_reviews.info() #Não há dados nulos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Unnamed: 0    99224 non-null  int64 
 1   review_id     99224 non-null  object
 2   order_id      99224 non-null  object
 3   review_score  99224 non-null  int64 
dtypes: int64(2), object(2)
memory usage: 3.0+ MB


In [13]:
df_reviews.drop(columns={'Unnamed: 0'}, inplace=True)
df_reviews.head()

review_id  ... review_score
0  7bc2406110b926393aa56f80a40eba40  ...            4
1  80e641a11e56f04c1ad469d5645fdfde  ...            5
2  228ce5500dc1d8e020d8d1322874b6f0  ...            5
3  e64fb393e7b32834bb789ff8bb30750e  ...            5
4  f7c4243c7fe1938f181bec41a392bdeb  ...            5

[5 rows x 3 columns]

In [14]:
df_reviews['review_score'].value_counts() #Imensa maioria das reviews são positivas

5    57328
4    19142
1    11424
3     8179
2     3151
Name: review_score, dtype: int64

##3.2. Dataset Itens

In [15]:
df_itens.describe() #Desvio padrão muito alto, média bem diferente da mediana (valores se concentram em preços mais baixos)

Unnamed: 0  order_item_id      price
count  112650.000     112650.000 112650.000
mean    56324.500          1.198    120.654
std     32519.398          0.705    183.634
min         0.000          1.000      0.850
25%     28162.250          1.000     39.900
50%     56324.500          1.000     74.990
75%     84486.750          1.000    134.900
max    112649.000         21.000   6735.000

In [16]:
df_itens.drop(columns={'Unnamed: 0'}, inplace=True)
df_itens.head()

order_id  ...   price
0  00010242fe8c5a6d1ba2dd792cb16214  ...  58.900
1  00018f77f2f0320c557190d7a144bdd3  ... 239.900
2  000229ec398224ef6ca0657da4fc703e  ... 199.000
3  00024acbcdf0a6daa1e931b038114c75  ...  12.990
4  00042b26cf59d7ce69dfabb4e55b4fd9  ... 199.900

[5 rows x 4 columns]

In [17]:
df_itens = df_itens.groupby(by=['order_id', 'product_id'], as_index=False) \
  .agg({'price': np.sum, 'order_item_id':np.max})
df_itens.head()

order_id  ... order_item_id
0  00010242fe8c5a6d1ba2dd792cb16214  ...             1
1  00018f77f2f0320c557190d7a144bdd3  ...             1
2  000229ec398224ef6ca0657da4fc703e  ...             1
3  00024acbcdf0a6daa1e931b038114c75  ...             1
4  00042b26cf59d7ce69dfabb4e55b4fd9  ...             1

[5 rows x 4 columns]

In [18]:
df_itens.shape

(102425, 4)

In [19]:
# Verificando os produtos mais vendidos

df_top_products = df_itens.groupby(by='product_id', as_index=False) \
  .agg({'order_item_id': np.sum}) \
  .rename(columns={'order_item_id':'qtd'}) \
  .set_index('product_id') \
  .sort_values('qtd', ascending = False)

##3.3. Dataset Orders

In [20]:
df_orders.drop(columns={'Unnamed: 0'}, inplace=True)
df_orders['order_status'].value_counts()

delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: order_status, dtype: int64

In [21]:
colunas_removidas = ["canceled", "unavailable", "invoiced", "processing", "created", "approved"]

In [22]:
df_orders['order_status']=df_orders['order_status'].apply(lambda x: 1 if x=="delivered" or x=="shipped" else 0)
df_orders['order_status'].value_counts()

1    97585
0     1856
Name: order_status, dtype: int64

##3.4. Dataset Products

In [23]:
df_products.drop(columns={'Unnamed: 0'}, inplace=True)
df_products.describe()

product_name_lenght  ...  product_width_cm
count            32341.000  ...         32949.000
mean                48.477  ...            23.197
std                 10.246  ...            12.079
min                  5.000  ...             6.000
25%                 42.000  ...            15.000
50%                 51.000  ...            20.000
75%                 57.000  ...            30.000
max                 76.000  ...           118.000

[8 rows x 6 columns]

In [24]:
df_products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   product_id                  32951 non-null  object 
 1   product_category_name       32341 non-null  object 
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_weight_g            32949 non-null  float64
 5   product_length_cm           32949 non-null  float64
 6   product_height_cm           32949 non-null  float64
 7   product_width_cm            32949 non-null  float64
dtypes: float64(6), object(2)
memory usage: 2.0+ MB


In [25]:
df_products.head()

product_id  ... product_width_cm
0  1e9e8ef04dbcff4541ed26657ea517e5  ...           14.000
1  3aa071139cb16b67ca9e5dea641aaa2f  ...           20.000
2  96bd76ec8810374ed1b65e291975717f  ...           15.000
3  cef67bcfe19066a932b7673e239eb23d  ...           26.000
4  9dc1a7de274444849c219cff195d0b71  ...           13.000

[5 rows x 8 columns]

#4. Estruturação dos dados
Quais devem ser os dados de Treino? E os de Teste? Preciso juntar as informações entre as tabelas?

##4.1. Unificando as tabelas

In [26]:
df = df_itens.merge(df_orders, how='inner', on='order_id')
df.shape

(102425, 6)

In [27]:
df = df.merge(df_reviews, how='inner', on='order_id')
df.shape

(102230, 8)

In [28]:
df = df.merge(df_products, how='inner', on='product_id')
df.shape

(102230, 15)

In [29]:
df_merge = df.copy()

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 102230 entries, 0 to 102229
Data columns (total 15 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   order_id                    102230 non-null  object 
 1   product_id                  102230 non-null  object 
 2   price                       102230 non-null  float64
 3   order_item_id               102230 non-null  int64  
 4   customer_id                 102230 non-null  object 
 5   order_status                102230 non-null  int64  
 6   review_id                   102230 non-null  object 
 7   review_score                102230 non-null  int64  
 8   product_category_name       100773 non-null  object 
 9   product_name_lenght         100773 non-null  float64
 10  product_description_lenght  100773 non-null  float64
 11  product_weight_g            102214 non-null  float64
 12  product_length_cm           102214 non-null  float64
 13  product_height

In [31]:
df.head(10)

order_id  ... product_width_cm
0  00010242fe8c5a6d1ba2dd792cb16214  ...           14.000
1  130898c0987d1801452a8ed92a670612  ...           14.000
2  532ed5e14e24ae1f0d735b91524b98b9  ...           14.000
3  6f8c31653edb8c83e1a739408b5ff750  ...           14.000
4  7d19f4ef4d04461989632411b7e588b9  ...           14.000
5  a0f9acf0b6294ed8561e32cde1a966bc  ...           14.000
6  bbf796534aaf9c59f8da8c7982db56e0  ...           14.000
7  c9ef97d2854afe64a3b4488bc2836af6  ...           14.000
8  df2d910b8b5e5f461f67043489f9569d  ...           14.000
9  00018f77f2f0320c557190d7a144bdd3  ...           40.000

[10 rows x 15 columns]

#5.Tratamento
Como pode ser feita a seleção e filtragem dos dados? Quais tratamentos devem ser feitos considerando os dados existentes?

In [32]:
df['order_status'].replace(0, np.nan, inplace=True)
df.dropna(subset=['order_status'], inplace=True)
df.shape

(101146, 15)

In [33]:
df.drop(columns='order_status', inplace=True)
df.head()

order_id  ... product_width_cm
0  00010242fe8c5a6d1ba2dd792cb16214  ...           14.000
1  130898c0987d1801452a8ed92a670612  ...           14.000
2  532ed5e14e24ae1f0d735b91524b98b9  ...           14.000
3  6f8c31653edb8c83e1a739408b5ff750  ...           14.000
4  7d19f4ef4d04461989632411b7e588b9  ...           14.000

[5 rows x 14 columns]

#6. Criação do Modelo
Desenvolva o modelo!

In [34]:
df_Tratado = df.copy()

In [35]:
df_Tratado.shape

(101146, 14)

#6.1. Código para pegar os itens mais vendidos

In [36]:
df.head()

order_id  ... product_width_cm
0  00010242fe8c5a6d1ba2dd792cb16214  ...           14.000
1  130898c0987d1801452a8ed92a670612  ...           14.000
2  532ed5e14e24ae1f0d735b91524b98b9  ...           14.000
3  6f8c31653edb8c83e1a739408b5ff750  ...           14.000
4  7d19f4ef4d04461989632411b7e588b9  ...           14.000

[5 rows x 14 columns]

In [37]:
top_itens_quantidade = df.groupby(by='product_id', as_index=False) \
  .agg({'order_item_id':np.sum, 'price':np.sum}) \
  .rename(columns = {'order_item_id':'quantidade vendida', 'price':'preço total'}) \
  .set_index('product_id') \
  .sort_values('quantidade vendida', ascending=False)
top_itens_quantidade.head(10)

quantidade vendida  preço total
product_id                                                       
aca2eb7d00ea1a7b8ebd4e68314663af                 526    37389.000
422879e10f46682990de24d770e7f83d                 515    26680.120
99a4788cb24856965c36a24e339b6058                 513    42306.360
389d119b48cf3043d311335e499d9c6b                 419    21336.790
368c6c730842d78016ad823897a372db                 407    21072.800
53759a2ecddad2bb87a079a1f1519f73                 403    20391.200
d1c427060a0f73f6b889a5c7c61f2ac4                 344    46618.510
53b36df67ebb7c41585e8d54d6772e08                 325    37312.740
154e7e31ebfa092203795c972e5804a6                 294     6573.080
3dd2a17168ec895c781a9191c1e95ad7                 273    40782.800

In [38]:
top_itens_receita = df.groupby(by='product_id', as_index=False) \
  .agg({'order_item_id':np.sum, 'price':np.sum}) \
  .rename(columns = {'order_item_id':'quantidade vendida', 'price':'preço total'}) \
  .set_index('product_id') \
  .sort_values('preço total', ascending=False)
top_itens_receita.head(10)

quantidade vendida  preço total
product_id                                                       
bb50f2e236e5eea0100680137654686c                 196    64210.000
6cdd53843498f92890544667809f1595                 156    54380.300
d6160fb7873f184099d9bc95e30376af                  34    47249.350
d1c427060a0f73f6b889a5c7c61f2ac4                 344    46618.510
99a4788cb24856965c36a24e339b6058                 513    42306.360
3dd2a17168ec895c781a9191c1e95ad7                 273    40782.800
25c38557cf793876c5abdd5931f922db                  38    37908.320
5f504b3a1c75b73d6151be81eb05bdc9                  64    37733.900
aca2eb7d00ea1a7b8ebd4e68314663af                 526    37389.000
53b36df67ebb7c41585e8d54d6772e08                 325    37312.740

##6.2. Clientes que mais compraram

In [39]:
df.head()

order_id  ... product_width_cm
0  00010242fe8c5a6d1ba2dd792cb16214  ...           14.000
1  130898c0987d1801452a8ed92a670612  ...           14.000
2  532ed5e14e24ae1f0d735b91524b98b9  ...           14.000
3  6f8c31653edb8c83e1a739408b5ff750  ...           14.000
4  7d19f4ef4d04461989632411b7e588b9  ...           14.000

[5 rows x 14 columns]

In [40]:
top_clientes_quantidade = df.groupby(by='customer_id', as_index=False) \
  .agg({'order_item_id':np.sum, 'price':np.sum}) \
  .rename(columns = {'order_item_id':'quantidade vendida', 'price':'preço total'}) \
  .set_index('customer_id') \
  .sort_values('quantidade vendida', ascending=False)
top_clientes_quantidade.head(10)

quantidade vendida  preço total
customer_id                                                      
be1c4e52bb71e0c54b11a26b8e8d59f2                  82     1430.160
fc3d1daec319d62d49bfb5e1f83123e9                  52       31.800
0d861a5e4dd6a9079d89e1330848f0ab                  43     1138.300
daf15f1b940cc6a72ba558f093dc00dd                  31      958.800
a67a246af6ba598a14cc86df3c0354ee                  28      563.000
30bb84b541c96af98ba7d90b9ebf35d0                  28     1093.000
1205480caca6c37f55954da838933b8a                  28      186.590
50920f8cd0681fd86ebe93670c8fe52e                  26      306.770
679f84ceb2ee4ca5bca0c3ea34647746                  26      479.200
a828c4f615a8dd8518659d867b3012bd                  25      635.380

##6.3. Funções base para cálculo de similaridade

In [41]:
# Faz uma cópia para que o dataset original não seja alterado
def start_pipeline(df):
    return df.copy()

# Agrupa o dateset por usuários e conta quantos livros diferentes cada um tem
# Ordena para que os usuários com mais livros fiquem no topo do dataset
def get_user_counts(df): 
  return df.groupby(by='customer_id', as_index=False) \
    .agg({'product_id': pd.Series.nunique}) \
    .rename(columns={'product_id': 'product_id_count'}) \
    .set_index('customer_id') \
    .sort_values('product_id_count', ascending = False)

# Agrupa o dateset por livros e conta quantos usuários diferentes cada lirvro tem
# Ordena para que os livros com mais usuários diferentes fiquem no topo do dataset
def get_product_counts(df): 
  return df.groupby(by='product_id', as_index=False) \
    .agg({'customer_id': pd.Series.nunique}) \
    .rename(columns={'customer_id': 'customer_id_count'}) \
    .set_index('product_id') \
    .sort_values('customer_id_count', ascending = False)

def get_product_review(df): 
  return df.groupby(by='product_id', as_index=False) \
    .agg({'review_score': np.mean}) \
    .rename(columns={'review_score': 'review'}) \
    .set_index('product_id') \
    .sort_values('review', ascending = False)

#Recebe o dataset e o tamanho da amostra
 # Retorna as n primeiras linhas do dataset recebido em formato de lista
def get_n_top_values(df, n): 
  return df.head(sample_size) \
    .index \
    .tolist()

 # Executa as funções acima para rankear os usuários
sample_size = 100
top_user_ids = df \
  .pipe(start_pipeline) \
  .pipe(get_user_counts) \
  .pipe(get_n_top_values, sample_size)

# Executa as funções acima para rankear os produtos mais vendidos
sample_size = 99
top_product_ids = df \
  .pipe(start_pipeline) \
  .pipe(get_product_counts) \
  .pipe(get_n_top_values, sample_size)

# Executa as funções acima para rankear os produtos mais bem avaliados
sample_size = 97
top_product_review = df \
  .pipe(start_pipeline) \
  .pipe(get_product_review) \
  .pipe(get_n_top_values, sample_size)

###6.3.1. Matriz de similaridade para clientes

In [42]:
#Transforma a amostra em um dataset, renomeando as colunas.
def transform_sample(df):
  return pd.DataFrame({
      "user": df["customer_id"],
      "product": df["product_id"],
      "purchase": df["order_item_id"]
  })

# Seleciona só os User-IDs que estão entre os top Users, transforma amostra em um dataframe e organiza o dataset em uma matriz Cliente x Produto 
matriz_de_relacionamento_user_sampled = df[df["customer_id"].isin(top_user_ids)] \
  .pipe(transform_sample) \
  .pivot_table(index="user", columns="product", values="purchase").fillna(0)

In [43]:
matriz_de_relacionamento_user_sampled

product                           0011c512eb256aa0dbbb544d8dffcf6e  ...  fef0dd8c53552d0f784b7cc5375a3ffe
user                                                                ...                                  
00ca6e4277e535d41bda84d371310be2                             0.000  ...                             0.000
09cc193befa14d698869667e92148ab2                             0.000  ...                             0.000
0a4a8ee3c788108918b12f21435c950c                             0.000  ...                             0.000
0aad2e31b3c119c26acb8a47768cd00a                             0.000  ...                             0.000
0d861a5e4dd6a9079d89e1330848f0ab                             0.000  ...                             0.000
...                                                            ...  ...                               ...
f0c0ed957add2cc4abeb60ade9ad6d19                             0.000  ...                             0.000
f6af2b95b6be76fe88673d0a62a7db2f                             0.000  ...                             0.000
f73d378096054953caa2d69a8abceb73                             0.000  ...                             3.000
febf66a130bc1bc3d35546f466261511                             0.000  ...                             0.000
fee8071ecc5ad2f5b2831c4fbd9b3cdd                             0.000  ...                             0.000

[100 rows x 416 columns]

In [44]:
from sklearn.metrics.pairwise import cosine_similarity

# Calculando a similaridade entre os usuários através da multiplicação da matriz CxP pela sua transposta
cos_user = cosine_similarity(matriz_de_relacionamento_user_sampled)
#Imprimindo o resultado
cos_user.sum()

106.15011306983709

###6.3.2. Matriz de Similaridade de produto

In [45]:
matriz_de_relacionamento_product_sampled = df[df["product_id"].isin(top_product_ids)] \
  .pipe(transform_sample) \
  .pivot_table(index="user", columns="product", values="purchase").fillna(0)

In [46]:
matriz_de_relacionamento_product_sampled.T.head(10)

user                              00066ccbe787a588c52bd5ff404590e3  ...  fffb97495f78be80e2759335275df2aa
product                                                             ...                                  
06edb72f1e0c64b14c5b79353f7abea3                             0.000  ...                             0.000
08574b074924071f4e201e151b152b4e                             0.000  ...                             0.000
0a57f7d2c983bcf8188589a5fea4a8da                             0.000  ...                             0.000
0aabfb375647d9738ad0f7b4ea3653b1                             0.000  ...                             0.000
0bcc3eeca39e1064258aa1e932269894                             0.000  ...                             0.000
154e7e31ebfa092203795c972e5804a6                             0.000  ...                             0.000
1613b819ab5dae53aead2dbb4ebdb378                             0.000  ...                             0.000
165f86fe8b799a708a20ee4ba125c289                             0.000  ...                             0.000
18b0e642cbae7251e60a64aa07dd9eb9                             0.000  ...                             0.000
19c91ef95d509ea33eda93495c4d3481                             0.000  ...                             0.000

[10 rows x 12561 columns]

In [47]:
# Calculando a similaridade entre os livros através da multiplicação da matriz Produto x Cliente pela sua transposta 
cos_item = cosine_similarity(matriz_de_relacionamento_product_sampled.T)
# Imprimindo o resultado
print(cos_item)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [48]:
cos_item.sum()

103.23977176982498

##6.4. Testando o modelo

###6.4.1. Recomendação para produtos mais similares

In [52]:
corr_items = np.corrcoef(matriz_de_relacionamento_product_sampled.T)

produto_de_interesse = matriz_de_relacionamento_product_sampled.T.index[-1]

print(f"Produto de interesse: {produto_de_interesse}")

produto_idx = matriz_de_relacionamento_product_sampled.T.index.tolist().index(produto_de_interesse)
print(f"Produto de id: {produto_de_interesse},tem índice {produto_idx}")

closest_10_products = np.argsort(-corr_items[produto_idx])[:10]

for i in zip(matriz_de_relacionamento_product_sampled.T.index[closest_10_products], corr_items[produto_idx][closest_10_products]):
    print(f"Produto {i[0]} tem similaridade {i[1]:.5f} com produto {produto_de_interesse}")

Produto de interesse: fb55982be901439613a95940feefd9ee
Produto de id: fb55982be901439613a95940feefd9ee,tem índice 98
Produto fb55982be901439613a95940feefd9ee tem similaridade 1.00000 com produto fb55982be901439613a95940feefd9ee
Produto dbb67791e405873b259e4656bf971246 tem similaridade -0.00440 com produto fb55982be901439613a95940feefd9ee
Produto 5a6e53c3b4e8684b13388d6aa4afdf12 tem similaridade -0.00497 com produto fb55982be901439613a95940feefd9ee
Produto cec09725da5ed01471d9a505e7389d37 tem similaridade -0.00526 com produto fb55982be901439613a95940feefd9ee
Produto 93c902b021a9e594f658ab1b0351602a tem similaridade -0.00531 com produto fb55982be901439613a95940feefd9ee
Produto 43423cdffde7fda63d0414ed38c11a73 tem similaridade -0.00532 com produto fb55982be901439613a95940feefd9ee
Produto 2948658cb6abc82847412be7201bfc4c tem similaridade -0.00533 com produto fb55982be901439613a95940feefd9ee
Produto ab1f9387c0627dd24000bfbc54fdeee0 tem similaridade -0.00540 com produto fb55982be901439613a95

###6.4.2. Recomendação para clientes mais similares

In [51]:
corr_users = np.corrcoef(matriz_de_relacionamento_user_sampled)

user_de_interesse = matriz_de_relacionamento_user_sampled.index[-1]

print(f"User de interesse: {user_de_interesse}")

user_idx = matriz_de_relacionamento_user_sampled.index.tolist().index(user_de_interesse)
print(f"User de id: {user_de_interesse},tem índice {user_idx}")

closest_10_users = np.argsort(-corr_users[user_idx])[:10]

for i in zip(matriz_de_relacionamento_user_sampled.index[closest_10_users], corr_users[user_idx][closest_10_users]):
    print(f"User {i[0]} tem similaridade {i[1]:.5f} com user {user_de_interesse}")

User de interesse: fee8071ecc5ad2f5b2831c4fbd9b3cdd
User de id: fee8071ecc5ad2f5b2831c4fbd9b3cdd,tem índice 99
User fee8071ecc5ad2f5b2831c4fbd9b3cdd tem similaridade 1.00000 com user fee8071ecc5ad2f5b2831c4fbd9b3cdd
User 12560c8fc6ef4609768854c0dec45c80 tem similaridade -0.00675 com user fee8071ecc5ad2f5b2831c4fbd9b3cdd
User 837bffa34c99bc9aed29abf1b5bdd886 tem similaridade -0.00709 com user fee8071ecc5ad2f5b2831c4fbd9b3cdd
User e804e7ef5f81657fd973fde6a032d3f4 tem similaridade -0.00709 com user fee8071ecc5ad2f5b2831c4fbd9b3cdd
User 6c185ed34983b0d80f77402efb2453bc tem similaridade -0.00709 com user fee8071ecc5ad2f5b2831c4fbd9b3cdd
User 00ca6e4277e535d41bda84d371310be2 tem similaridade -0.00709 com user fee8071ecc5ad2f5b2831c4fbd9b3cdd
User a51ebdfce7cdd6930370083085f240c6 tem similaridade -0.00709 com user fee8071ecc5ad2f5b2831c4fbd9b3cdd
User 2e70fb007f814f4e0bc167ca49d271f6 tem similaridade -0.00709 com user fee8071ecc5ad2f5b2831c4fbd9b3cdd
User 8c4a739a0897f0706505e419d7f1e4ac tem 

#7. Ajustes no Portfólio
O que pode ser melhorado para que o portfólio seja bem explicativo e estruturado?

Para melhorar o portfólio poderíamos colocar todo o desenvolvimento deste notebook em um arquivo .py para que fique mais fácil para o usuário utilizar o modelo de recomendação e visualizar o que está sendo feito. Além disso, a parte do código referente a análise exploratória não precisa obrigatoriamente fazer parte do modelo, pode ser inserida como um arquivo anexo justificando as escolhas feitas ao longo do nosso desenvolvimento.